[server]
protocol = http
http_addr = 0.0.0.0
http_port = 3030
domain = localhost
root_url = http://localhost:3030

[security]
admin_user = admin
admin_password = admin

[auth]
disable_login_form = false

[auth.anonymous]
enabled = true
org_role = Viewer

[paths]
data = /var/lib/grafana/data
logs = /var/lib/grafana/logs
plugins = /var/lib/grafana/plugins

[log]
mode = console
level = info

[datasources]
; Configuração automática via provisioning